# Generated by Django 3.0.8 on 2020-09-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('key', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('Cakes', 'Cakes'), ('Cupcakes', 'Cupcakes'), ('Tarts', 'Tarts'), ('Chocolates', 'Chocolates'), ('Customized Cakes', 'Customized Cakes')], max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('key', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='review_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('key', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='review_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('key', models.FloatField(max_length=10)),
            ],
        ),
    ]
