# Generated by Django 3.0.8 on 2020-09-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu'),
        ),
        migrations.AlterField(
            model_name='review_images',
            name='image',
            field=models.ImageField(upload_to='review'),
        ),
    ]
