# Generated by Django 3.0.8 on 2020-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200929_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='quantity',
            field=models.CharField(max_length=10),
        ),
    ]
